[package]
name = "routine"
version = "0.1.0"
edition = "2024"
authors = ["Ernesto Men√©ndez <pyalec@gmail.com>"]

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
